CREATE TABLE TB011_PAGAMENTO(
    CO_PAGAMENTO SERIAL PRIMARY KEY,
    DE_STATUS VARCHAR(3) NOT NULL,
    NU_NIT VARCHAR(64) NOT NULL,
    CO_ORDEM VARCHAR(40) NOT NULL,
    CO_MERCHANTUSN NUMERIC(12) NOT NULL,
    VL_VALOR NUMERIC(10, 2) NOT NULL,
    CO_AUTORIZADORA NUMERIC(4) NOT NULL,
    DT_PAGAMENTO TIMESTAMP NOT NULL
 )
