CREATE TABLE TB012_TRANSACAO(
    CO_MERCHANTUSN SERIAL PRIMARY KEY,
    CO_ORDEM VARCHAR(40),
    NU_PARCELA NUMERIC(2) NOT NULL,
    TP_PARCELA NUMERIC(2) NOT NULL,
    CO_AUTORIZADORA NUMERIC(4) NOT NULL,
    VL_VALOR NUMERIC(10, 2) NOT NULL,
    DT_TRANSACAO TIMESTAMP NOT NULL,
    CO_TRANSACAO NUMERIC(3),
    DE_MENSAGEM VARCHAR(250),
    PAGAMENTO_CO INT,
    FOREIGN KEY (PAGAMENTO_CO) REFERENCES TB011_PAGAMENTO (CO_PAGAMENTO)
 )
